/** Real browser checks. Run npm run dev first. Requires a working Chromium installation. */
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
const page = await browser.newPage({ viewport: { width: 1512, height: 960 } });
await page.addInitScript(() => localStorage.setItem('guitario-auto-artwork', 'off'));
const errors = []; page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(process.env.GUITARIO_TEST_URL || 'http://127.0.0.1:5173');
  await page.getByRole('button', { name: 'Open Afterglow', exact: true }).waitFor();
  assert.equal(await page.locator('.song-card').count(), 3);
  assert.equal(await page.locator('.workspace').count(), 0);
  await page.screenshot({ path: 'test-results/01-library.png' });
  await page.getByRole('button', { name: 'Tunings', exact: true }).click();
  await page.getByRole('button', { name: 'Open Drop D collection', exact: true }).click();
  assert.equal(await page.locator('.song-card').count(), 1);
  await page.getByRole('button', { name: /All songs/ }).click();
  await page.getByRole('textbox', { name: 'Search library' }).fill('heavy');
  assert.equal(await page.locator('.song-card').count(), 1);
  await page.getByRole('button', { name: 'Clear search' }).click();

  await page.getByRole('button', { name: 'Create folder', exact: true }).click();
  await page.getByRole('textbox', { name: 'Folder name', exact: true }).fill('Current set');
  await page.getByRole('button', { name: 'Save folder', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Afterglow details', exact: true }).click();
  await page.getByRole('combobox', { name: 'Song folder', exact: true }).selectOption({ label: 'Current set' });
  await page.getByRole('checkbox', { name: '6-string acoustic', exact: true }).check();
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await page.getByRole('button', { name: 'Open Afterglow', exact: true }).click();
  await page.getByRole('button', { name: 'Select bar 24', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Update Intro progress', exact: true }).click();
  await page.getByRole('combobox', { name: 'Learning status' }).selectOption('learning');
  await page.getByRole('slider', { name: 'Percentage learnt' }).evaluate(el => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, '65'); el.dispatchEvent(new Event('input', { bubbles: true })); });
  await page.getByRole('button', { name: 'Save section', exact: true }).click();
  await page.locator('.section-list .status-mark.learning').filter({ hasText: '65%' }).waitFor();
  await page.getByRole('button', { name: /^Song map/ }).click();
  await page.getByRole('dialog', { name: 'Song map', exact: true }).waitFor();
  await page.screenshot({ path: 'test-results/02-song-map.png' });
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Open Afterglow', exact: true }).click();
  await page.locator('.section-list .status-mark.learning').filter({ hasText: '65%' }).waitFor();
  await page.getByRole('button', { name: 'Add recording', exact: true }).click();
  await page.getByRole('dialog', {name:'Add recording'}).waitFor();
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('button', { name: 'Your library', exact: true }).click();

  const dense = Array(16).fill('(10.6 12.5 12.4).16').join(' ');
  const source = '\\title "Long score study" \\artist "Test" \\tempo 86 . ' + Array.from({ length: 115 }, (_, i) => i % 3 ? dense : '0.6.1').join(' | ');
  await page.locator('#import-files').setInputFiles({ name: 'long-study.alphatex', mimeType: 'text/plain', buffer: Buffer.from(source) });
  await page.getByRole('dialog', { name: 'Review import' }).waitFor(); await page.getByRole('button', { name: /^Import [0-9]+ songs?$/ }).click();
  await page.getByRole('button', { name: 'Open Long score study', exact: true }).click();
  await page.getByRole('button', { name: 'Select bar 115', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Select bar 1', exact: true }).click();
  await page.getByRole('button', { name: 'Select bar 4', exact: true }).click({ modifiers: ['Shift'] });
  await page.getByRole('button', { name: 'Create section', exact: true }).click();
  await page.getByRole('textbox', { name: 'Section name', exact: true }).fill('Intro');
  await page.getByRole('button', { name: 'Save section', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Intro', exact: true }).waitFor();
  await page.getByRole('button', {name:'Player settings',exact:true}).click();
  await page.getByRole('combobox', { name: 'Notation spacing' }).selectOption('1.8');
  await page.getByRole('button', { name: 'Select bar 115', exact: true }).waitFor();
  await page.screenshot({ path: 'test-results/03-focused-score.png' });
  await page.getByRole('button', { name: 'Suggest sections', exact: true }).click();
  await page.getByRole('dialog', { name: 'Suggested sections', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Loop selected bars', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('[aria-label="Play"]')?.disabled);
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await page.getByRole('button', { name: 'Pause', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Pause', exact: true }).click();

  await page.getByRole('button', { name: 'Your library', exact: true }).click();
  await page.getByRole('button', { name: 'Backups', exact: true }).click();
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export', exact: true }).click();
  await (await pending).saveAs('test-results/library-backup.json');
  await page.locator('#restore-file').setInputFiles('test-results/library-backup.json');
  await page.getByRole('button', { name: 'Add new songs only', exact: true }).click();
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('button', { name: 'Open Long score study', exact: true }).click();
  await page.setViewportSize({ width: 1100, height: 760 });
  await page.screenshot({ path: 'test-results/04-small-window.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name: 'Your library', exact: true }).click();
  await page.getByRole('button', { name: 'Delete Long score study', exact: true }).click();
  await page.getByRole('button', { name: 'Delete song', exact: true }).click();
  await page.getByRole('button', { name: 'Open Afterglow', exact: true }).waitFor();
  assert.equal(await page.locator('.song-card').count(), 3);
  assert.deepEqual(errors, []);
  console.log('PASS: home, filters, folders, sections, learning %, persistence, long scores, synth transport, backup and deletion.');
} finally { await browser.close(); }
