import {chromium,_electron as electron} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import * as alphaTab from '@coderline/alphatab';
import {checkSongDetails} from './song-details-check.mjs';
const root=path.resolve('dist'),server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));fs.mkdirSync('test-results',{recursive:true});
const desktop=process.argv.includes('--desktop'),version=JSON.parse(fs.readFileSync('package.json','utf8')).version;
const profile=desktop?fs.mkdtempSync(path.resolve('test-results/desktop-v1-')):undefined;
const browser=desktop?await electron.launch({executablePath:process.env.GUITARIO_DESKTOP_EXECUTABLE || path.resolve(`../../Guitar-io-${version}-Windows-x64/Guitar.io.exe`),env:{...process.env,GUITARIO_TEST_PROFILE:profile}}):await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=desktop?await browser.firstWindow():await browser.newPage({viewport:{width:1512,height:960}}),errors=[];
await page.addInitScript(()=>localStorage.setItem('guitario-auto-artwork','off'));page.on('pageerror',e=>errors.push(e.message));
const button=(name,target=page)=>target.getByRole('button',{name,exact:true});
const url=desktop?'guitario://app/':`http://127.0.0.1:${server.address().port}/`;
const score=alphaTab.importer.ScoreLoader.loadAlphaTex('\u005c\u005ctitle "Quiet study" \u005c\u005cartist "Test band" \u005c\u005ctempo 360 . \u005c\u005ctrack "Bass" \u005c\u005cinstrument 34 \u005c\u005ctuning G2 D2 A1 E1 0.4.1 | 1.4.1 | 2.4.1 | 3.4.1 \u005c\u005ctrack "Lead guitar" \u005c\u005cinstrument 29 \u005c\u005ctuning E4 B3 G3 D3 A2 E2 0.6.1 | 1.6.1 | 2.6.1 | 3.6.1');
score.masterBars[0].isRepeatStart=true;score.masterBars[1].repeatCount=2;score.rebuildRepeatGroups();
const bytes=Buffer.from(new alphaTab.exporter.Gp7Exporter().export(score));
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
async function stored(){return page.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('guitar-io-v1');q.onsuccess=()=>r(q.result);});return new Promise(r=>{const q=db.transaction('songs').objectStore('songs').getAll();q.onsuccess=()=>{db.close();r(q.result);};});});}
async function ready(){await button('Select bar 4').waitFor();await page.waitForFunction(()=>!document.querySelector('[aria-label=Play]')?.disabled && !document.querySelector('.loading-score'));}
async function importTab(buffer=bytes){await page.locator('#import-files').setInputFiles({name:'quiet.gp',mimeType:'application/octet-stream',buffer});await page.getByRole('dialog',{name:'Review import',exact:true}).waitFor();}
try{
  await page.goto(url);await page.getByText('Start by adding your first guitar',{exact:true}).waitFor();assert.equal(await page.locator('.song-card').count(),0);assert.equal((await stored()).length,0);
  assert.equal(await page.getByText('Saved on this device',{exact:true}).count(),0);assert.equal(await page.locator('.version').count(),0);
  await button('Add guitar').click();await page.getByLabel('Guitar name',{exact:true}).fill('Test ESP');assert(!await page.getByLabel('Material / woods').isVisible());await page.locator('.guitar-extra-details summary').click();await page.getByLabel('Pickups',{exact:true}).fill('Bridge humbucker');assert.equal(await page.locator('.string-gauges input').count(),6);await page.getByLabel('String 1 gauge').fill('10');await page.getByLabel('Guitar strings').selectOption('7');assert.equal(await page.locator('.string-gauges input').count(),7);await page.getByLabel('Guitar strings').selectOption('6');
  await button('Add tuning').click();await button('DROP').click();await page.getByLabel('Tuning preset').selectOption('guitar-6-Drop--3');await button('Use this tuning').click();await button('Save guitar').click();await page.getByText('Add your first song',{exact:true}).waitFor();
  await button('Add songs').click();await page.locator('.format-info').hover();await page.getByRole('tooltip').waitFor({state:'visible'});await button('Close dialog').click();
  await importTab();assert.equal(await page.getByLabel('Import instrument').count(),0);assert.equal(await button('Find missing artwork').count(),1);assert.equal(await page.getByLabel('Upload artwork').count(),1);assert.equal(await page.getByLabel('Import tags').count(),0);
  await page.getByLabel('Import tuning label').selectOption('Drop B');await button('Add tag').click();await page.getByLabel('New tag').fill('Heavy');await page.getByLabel('New tag').press('Enter');await button('Import 1 song').click();await button('Open Quiet study').waitFor();let song=(await stored())[0];assert.equal(song.trackIndex,1);assert.equal(song.tuning,'Drop B');assert(song.sourceTunings);assert.deepEqual(song.tags,['Heavy']);assert.equal(song.tracks[1].notes,'B1 · Gb2 · B2 · E3 · Ab3 · Db4');
  await button('Search library').click();await page.getByLabel('Search library text').fill('Quiet');assert.equal(await page.locator('.song-card').count(),1);await button('Clear search').click();await button('Filters and sort').click();await page.getByLabel('Filter difficulty').selectOption('unrated');await button('Filters and sort').click();await button('List view').click();await page.evaluate(()=>document.querySelector('.collection-main').scrollTop=10000);assert(await page.locator('.library-views').evaluate(el=>getComputedStyle(el).position==='fixed'));
  await page.evaluate(()=>{const Native=window.alphaTab.AlphaTabApi;window.alphaTab.AlphaTabApi=new Proxy(Native,{construct(Target,args){const api=new Target(...args);window.__testApi=api;return api;}});});
  await button('Open Quiet study').click();await ready();assert.equal(await page.getByLabel('Instrument track').count(),0);assert.equal(await button('Change instrument tuning').count(),1);assert.equal(await button('Create section').count(),1);assert.equal(await page.locator('.transport .create-section').count(),0);
  await button('Select bar 2').click();await button('Select bar 3').click({modifiers:['Shift']});assert.equal(await page.locator('.bar-overlay.selected').count(),2);await button('Player settings').click();assert.equal(await page.getByLabel('Notation spacing').getAttribute('type'),'range');assert.deepEqual(await page.locator('[aria-label="Notation display"] button').allTextContents(),['Tab','Notation','Both']);
  assert(await page.evaluate(()=>{const p=document.querySelector('.integrated-player'),s=document.querySelector('.score-paper');return Number(getComputedStyle(p).zIndex)>Number(getComputedStyle(s).zIndex)&&getComputedStyle(s).isolation==='isolate';}));
  await page.getByLabel('Notation spacing').fill('1.8');await button('Dark mode').click();await page.waitForFunction(()=>document.querySelector('.dark-score .alpha-score svg'));assert.equal(await page.evaluate(()=>window.__testApi.settings.display.resources.mainGlyphColor.r),227);await page.screenshot({path:'test-results/v1-player-dark.png'});
  await button('Fullscreen score').click();await page.waitForFunction(()=>!!document.fullscreenElement);await button('Fullscreen score').click();await page.waitForFunction(()=>!document.fullscreenElement);await page.setViewportSize({width:1100,height:760});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/v1-player-small.png'});await page.setViewportSize({width:1512,height:960});await button('Player settings').click();await button('Loop selected bars').click();assert.equal(await button('Loop selected bars').innerText(),'');await page.evaluate(()=>{window.__loopVisits=[];window.__testApi.playedBeatChanged.on(beat=>{const bar=beat.voice.bar.index+1;if(window.__loopVisits.at(-1)!==bar)window.__loopVisits.push(bar);});});await page.keyboard.press('Space');await button('Pause').waitFor();await page.waitForFunction(()=>{const i=window.__loopVisits.indexOf(3);return i>=0 && window.__loopVisits.slice(i+1).includes(2);},null,{timeout:10000});await page.keyboard.press('Space');await button('Play').waitFor();await button('Loop selected bars').click();
  await button('Create section').click();assert.equal(await page.getByLabel('Learning status').count(),0);assert.equal(await page.getByLabel('Practice notes').count(),0);await page.getByLabel('Section name',{exact:true}).selectOption('Verse');assert.equal(await page.getByLabel('From bar',{exact:true}).inputValue(),'2');assert.equal(await page.getByLabel('To bar',{exact:true}).inputValue(),'3');await button('Save section').click();await button('Edit Verse').click();await page.getByLabel('Percentage learnt').fill('40');await button('Save section').click();await button('Undo notation edit').click();await button('Edit Verse').click();assert.equal(await page.getByLabel('Percentage learnt').inputValue(),'0');await page.getByLabel('Percentage learnt').fill('40');await button('Save section').click();await button('Edit Verse').click();await page.screenshot({path:'test-results/v1-section.png'});await button('Cancel section edit').click();
  await page.locator('.note-hit').first().click();await page.keyboard.press('1');await page.keyboard.press('1');await page.waitForFunction(()=>document.querySelector('.note-hit').getAttribute('aria-label').includes('fret 11'));await page.waitForTimeout(1050);await page.keyboard.press('2');await page.waitForFunction(()=>document.querySelector('.note-hit').getAttribute('aria-label').includes('fret 2'));
  await page.locator('.note-hit').first().click({button:'right'});assert.equal(await page.getByRole('menuitem',{name:'Transpose selected notes'}).count(),0);await page.getByRole('menuitem',{name:'Add text note',exact:true}).click();assert.equal(await page.getByRole('dialog').count(),0);await page.getByLabel('Text note',{exact:true}).fill('Play this smoothly');await page.getByLabel('Text note',{exact:true}).press('Enter');await page.waitForFunction(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('guitar-io-v1');q.onsuccess=()=>r(q.result);});const songs=await new Promise(r=>{const q=db.transaction('songs').objectStore('songs').getAll();q.onsuccess=()=>r(q.result);});db.close();return songs[0].annotations?.[0]?.text==='Play this smoothly';});
  await page.locator('.free-text-note').hover();await button('Highlight text note').click();await button('Highlight #94c4f2').click();await button('Move text note').press('ArrowRight');await page.screenshot({path:'test-results/v1-annotation.png'});
  await button('Change instrument tuning').click();assert.equal(await page.getByLabel('Pitch or tuning').count(),0);assert.equal(await button('Hear tuning').count(),0);assert(!await page.getByLabel('Retuning behavior').isVisible());await button('DROP').click();await page.getByLabel('Tuning preset').selectOption('guitar-6-Drop--4');await button('Apply tuning').click();await ready();song=(await stored())[0];assert.equal(song.tuning,'Drop B♭');assert.equal(Object.keys(song.tuningEdits).length,2);assert.equal((await page.evaluate(()=>window.__testApi.score.tracks[1].staves[0].tuning)).at(-1),34);
  await button('Player settings').click();await page.getByLabel('Instrument track').selectOption('0');await page.waitForTimeout(350);await button('Player settings').click();await button('Return to library').click();await button('Open Quiet study').click();await ready();assert.equal(await page.evaluate(()=>window.__testApi.tracks[0].index),0);await button('Return to library').click();
  await button('Tunings').click();assert.equal(await button('Open E standard collection').count(),1);assert.equal(await button('Open Drop B collection').count(),0);await button('All songs').click();await button('Open Quiet study').click();await ready();await button('Player settings').click();await page.getByLabel('Instrument track').selectOption('1');await page.waitForTimeout(350);await button('Player settings').click();await button('Return to library').click();await button('Tunings').click();assert.equal(await button('Open Drop B collection').count(),1);assert.equal(await button('Open Drop B♭ collection').count(),1);assert.equal(await page.locator('.collection-camera').count(),0);
  await button('Guitars').click();assert.equal(await button('Add songs').count(),0);await button('Open Test ESP collection').click();await button('Open Drop B collection').click();await button('Open Quiet study').click();await ready();await button('Change instrument tuning').click();await button('Restore original tuning').click();await ready();song=(await stored())[0];assert.equal(song.tuning,'Drop B');assert.equal(Object.keys(song.tuningEdits).length,0);assert.equal(song.noteEdits[Object.keys(song.noteEdits).find(k=>k.startsWith('1:') && k.split(':')[2]==='0')].fret,2);await button('Return to library').click();await button('All songs').click();
  const changed=alphaTab.importer.ScoreLoader.loadAlphaTex('\u005c\u005ctitle "Quiet study" \u005c\u005cartist "Test band" . 9.6.4');await importTab(Buffer.from(new alphaTab.exporter.Gp7Exporter().export(changed)));await page.getByText('This song may already exist.',{exact:false}).waitFor();await page.getByLabel('Import song title').fill('Quiet study alternate');assert.equal(await page.locator('.duplicate-warning').count(),0);await button('Cancel import').click();assert.equal((await stored()).length,1);
  await button('Edit Quiet study details').click();await page.getByRole('dialog',{name:'Song details',exact:true}).waitFor();assert.equal(await page.getByLabel('Vibes & custom tags').count(),0);assert.equal(await page.getByLabel('Upload artwork').count(),1);
  await page.route('https://musicbrainz.org/**',route=>route.fulfill({json:{recordings:[],releases:[]}}));await page.route('https://itunes.apple.com/**',route=>route.fulfill({json:{results:[{collectionName:'First album',artistName:'Test band',artworkUrl100:'https://is1-ssl.mzstatic.com/image/a/100x100bb.jpg'},{collectionName:'Second album',artistName:'Test band',artworkUrl100:'https://is1-ssl.mzstatic.com/image/b/100x100bb.jpg'}]}}));await page.route('https://en.wikipedia.org/**',route=>route.fulfill({json:{query:{pages:{1:{title:'Test band',terms:{description:['rock band']},thumbnail:{source:'https://upload.wikimedia.org/test/artist.png'}}}}}}));for(const pattern of ['https://*.mzstatic.com/**','https://upload.wikimedia.org/**'])await page.route(pattern,route=>route.fulfill({body:image,contentType:'image/png'}));
  await button('Find missing artwork').click();await button('Choose Second album artwork').waitFor();await button('Choose Second album artwork').click();await button('Save changes').click();await page.getByRole('dialog',{name:'Song details',exact:true}).waitFor({state:'detached'});song=(await stored())[0];assert.equal(song.album,'Second album');assert(song.artworkAssetId);assert(song.collectionArt['Artists:Test band']);
  await button('Artists').click();assert.equal(await button('Open Test band collection').count(),1);await page.getByLabel('Artwork for Test band').setInputFiles({name:'band.png',mimeType:'image/png',buffer:image});await page.waitForTimeout(200);await page.screenshot({path:'test-results/v1-library.png'});await button('Filters and sort').click();await page.getByLabel('Filter difficulty').selectOption('5');assert.equal(await button('Open Test band collection').count(),1);await page.getByLabel('Filter difficulty').selectOption('');await button('Filters and sort').click();await button('All songs').click();await button('Open Quiet study').click();await ready();
  await page.evaluate(()=>{window.YT={Player:class {constructor(_mount,options){this.time=0;this.state=2;this.rate=1;this.vol=75;queueMicrotask(()=>options.events.onReady({target:this}));}getCurrentTime(){return this.time;}getPlayerState(){return this.state;}getPlaybackRate(){return this.rate;}setPlaybackRate(v){this.rate=v;}getVolume(){return this.vol;}setVolume(v){this.vol=v;}seekTo(v){this.time=v;}playVideo(){this.state=1;}pauseVideo(){this.state=2;}destroy(){this.getCurrentTime=undefined;}}};});
  await button('Add recording').click();assert.equal(await page.getByLabel('New recording tags').count(),0);assert.equal(await page.getByLabel('New recording name').count(),0);await button('Backing track').click();await button('YouTube link').click();await page.getByLabel('YouTube video link').fill('https://www.youtube.com/watch?v=dQw4w9WgXcQ');await button('Add recording').last().click();await page.getByRole('dialog').waitFor({state:'detached'});song=(await stored())[0];assert.equal(song.media.recordings[0].label,'Backing track');assert.deepEqual(song.media.recordings[0].tags,[]);await page.getByRole('tab',{name:'MIDI',exact:true}).click();await ready();
  const popup=desktop?browser.waitForEvent('window'):page.waitForEvent('popup');await button('Learn').click();const learn=await popup;await learn.getByLabel('Learn song').waitFor();assert.deepEqual(await learn.locator('[aria-label="Learn song"] option').allTextContents(),['Scale library','Current song']);await learn.close();
  await button('Help').click();await page.getByText(`Guitar.io · Version ${version}`,{exact:true}).waitFor();await button('Backups').click();await page.getByRole('dialog',{name:'Keep your collection safe.',exact:true}).waitFor();await button('Close dialog').click();
  await button('Return to library').click();await page.reload();await button('Open Quiet study').waitFor();song=(await stored())[0];assert.equal(song.album,'Second album');assert.equal(song.annotations[0].text,'Play this smoothly');assert.equal(song.annotations[0].color,'#94c4f2');assert.deepEqual(song.annotationPositions[song.annotations[0].id].x>0,true);assert.deepEqual(errors,[]);
  await button('Help').click();await button('Backups').click();
  const backupPath=path.resolve('test-results/v1-backup.json');
  if(desktop){await browser.evaluate(({session},target)=>{globalThis.__backupState=null;session.defaultSession.once('will-download',(_event,item)=>{item.setSavePath(target);item.once('done',(_event,state)=>globalThis.__backupState=state);});},backupPath);await button('Export').click();for(let i=0;i<100 && await browser.evaluate(()=>globalThis.__backupState)===null;i++)await new Promise(r=>setTimeout(r,50));assert.equal(await browser.evaluate(()=>globalThis.__backupState),'completed');}
  else{const pending=page.waitForEvent('download');await button('Export').click();await (await pending).saveAs(backupPath);}
  const backup=JSON.parse(fs.readFileSync(backupPath,'utf8'));assert(backup.songs[0].sourceTunings);assert.equal(backup.guitars[0].pickups,'Bridge humbucker');assert.equal(backup.songs[0].annotations[0].free,true);
  await page.locator('#restore-file').setInputFiles(backupPath);await button('Restore & replace matches').click();await button('Close dialog').click();await button('Open Quiet study').waitFor();
  const detailsScore=alphaTab.importer.ScoreLoader.loadAlphaTex('\u005c\u005ctitle "Details study" . '+Array(24).fill('0.6.1').join(' | '));await importTab(Buffer.from(new alphaTab.exporter.Gp7Exporter().export(detailsScore)));await button('Import 1 song').click();await button('Open Details study').click();await button('Select bar 24').waitFor();await checkSongDetails(page);await button('Return to library').click();
  if(desktop){
    const details=await browser.evaluate(({app})=>({version:app.getVersion(),profile:app.getPath('userData')}));assert.equal(details.version,version);assert(details.profile.includes('desktop-v1-'));
    const provider=alphaTab.importer.ScoreLoader.loadAlphaTex('\u005c\u005ctitle "Hidden import study" . 0.6.4 2.6.4');const providerBytes=Array.from(new alphaTab.exporter.Gp7Exporter().export(provider));
    await browser.evaluate(async({net,session},bytes)=>{
      const original=net.fetch;net.fetch=(url,options)=>url==='https://www.songsterr-downloader.com/api/download/byRevisionJson'?Promise.resolve(new Response('<html>Verify</html>',{status:403,headers:{'Content-Type':'text/html'}})):original(url,options);
      globalThis.__providerHtml=`<!doctype html><form action="?/getMetadataFromTabUrl" onsubmit="event.preventDefault();setTimeout(()=>document.getElementById('gp').hidden=false,1000)"><input id="songsterr-url" oninput="document.getElementById('submit').disabled=false"><button id="submit" disabled>Download</button></form><button id="gp" hidden onclick="const a=document.createElement('a');a.href=window.URL.createObjectURL(new Blob([new Uint8Array(${JSON.stringify(bytes)})],{type:'application/gp'}));a.download='Hidden-import.gp';a.click()">Download Guitar Pro</button>`;
      globalThis.__providerStall=false;await session.fromPartition('songsterr-import').protocol.handle('https',()=>new Response(globalThis.__providerStall?'<!doctype html><p>Manual verification required</p>':globalThis.__providerHtml,{headers:{'Content-Type':'text/html'}}));
    },providerBytes);
    await button('Add songs').click();await page.getByLabel('Songsterr song link').fill('https://www.songsterr.com/a/wsa/hidden-import-study-tab-s123');const hidden=browser.waitForEvent('window');await button('Import').click();const downloader=await hidden;await downloader.waitForURL('https://www.songsterr-downloader.com/');
    assert.equal(await browser.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().startsWith('https://www.songsterr-downloader.com'))?.isVisible()),false);
    await page.getByRole('dialog',{name:'Review import',exact:true}).waitFor({timeout:15000});assert.equal(browser.windows().length,1);await button('Cancel import').click();
    await browser.evaluate(()=>{globalThis.__providerStall=true;});await button('Add songs').click();await page.getByLabel('Songsterr song link').fill('https://www.songsterr.com/a/wsa/hidden-import-study-tab-s123');const stalled=browser.waitForEvent('window');await button('Import').click();const fallback=await stalled;await fallback.waitForURL('https://www.songsterr-downloader.com/');
    assert.equal(await browser.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().startsWith('https://www.songsterr-downloader.com'))?.isVisible()),false);
    const start=Date.now();let shown=false;while(Date.now()-start<25000){shown=await browser.evaluate(({BrowserWindow})=>!!BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().startsWith('https://www.songsterr-downloader.com'))?.isVisible());if(shown)break;await new Promise(r=>setTimeout(r,250));}assert(shown);assert(Date.now()-start>=19000);assert.equal(await fallback.locator('form').count(),0);
    await browser.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().startsWith('https://www.songsterr-downloader.com'));await w.webContents.executeJavaScript(`document.body.innerHTML=${JSON.stringify(globalThis.__providerHtml.replace('<!doctype html>',''))}`);});
    await page.getByRole('dialog',{name:'Review import',exact:true}).waitFor({timeout:15000});await button('Import 1 song').click();await button('Open Hidden import study').waitFor();
    console.log('PASS: native Songsterr imports stay hidden during ordinary automatic steps, surface after 20 seconds of inactivity, leave verification untouched and resume to metadata review.');
  }
  assert.deepEqual(errors,[]);
  console.log(`PASS: ${desktop?'Windows':'Edge'} v1 onboarding, import corrections, artwork selection, duplicates, controls/layers, dark score, sections, note entry, free annotations, whole-score tuning/restore, both tuning buckets, profile specs, recording choices and current-song Learn.`);
}catch(e){await page.screenshot({path:'test-results/v1-failure.png'}).catch(()=>{});console.error((await page.locator('body').innerText()).slice(-3500));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));if(profile){assert(profile.startsWith(path.resolve('test-results')+path.sep));fs.rmSync(profile,{recursive:true,force:true});}}

