/** v1.0.1 long-score/reopen/layout regressions; every test profile is isolated. */
import {chromium,_electron as electron} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import * as alphaTab from '@coderline/alphatab';
const version=JSON.parse(fs.readFileSync('package.json','utf8')).version,root=path.resolve('dist');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));fs.mkdirSync('test-results',{recursive:true});
const desktop=process.argv.includes('--desktop'),diagnose=process.argv.includes('--diagnose');
const browser=desktop?await electron.launch({executablePath:process.env.GUITARIO_DESKTOP_EXECUTABLE || path.resolve(process.env.GUITARIO_OUTPUT_DIR || 'release/artifacts',`Guitar-io-${version}-Windows-x64/Guitar.io.exe`),env:{...process.env,GUITARIO_TEST_PROFILE:fs.mkdtempSync(path.resolve('test-results/desktop-v101-'))}}):await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=desktop?await browser.firstWindow():await browser.newPage({viewport:{width:1512,height:960}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('guitario-auto-artwork','off'));
const button=name=>page.getByRole('button',{name,exact:true});
const score=alphaTab.importer.ScoreLoader.loadAlphaTex('\\title "Long layout study" \\artist "Original test" . '+Array.from({length:115},(_,i)=>`(0.1 1.2 2.3 3.4 4.5 5.6).4 ${i%12}.1.4 3.2.4 2.3.4`).join(' | '));
for(const beat of score.tracks[0].staves[0].bars.flatMap(b=>b.voices[0].beats))for(const note of beat.notes)note.isPalmMute=true;
const marker=new alphaTab.model.Section();marker.text='IMPORTED SECTION HEADING';marker.marker='A';score.masterBars[0].section=marker;for(const [index,name] of [[28,'Learning phrase'],[57,'Comfortable phrase'],[86,'Mastered phrase']]){const section=new alphaTab.model.Section();section.text=name;score.masterBars[index].section=section;}
const bytes=Buffer.from(new alphaTab.exporter.Gp7Exporter().export(score));
async function ready(){await button('Select bar 115').waitFor();await page.waitForFunction(()=>!document.querySelector('.loading-score') && !document.querySelector('[aria-label=Play]')?.disabled);}
async function surfaces(){return page.evaluate(()=>{const host=document.querySelector('.alpha-score'),surfaces=[...host.querySelectorAll('.at-surface')];return {hosts:document.querySelectorAll('.alpha-score').length,surfaces:surfaces.length,parts:surfaces.flatMap(s=>[...s.children].map(e=>({id:e.layoutResultId,x:parseFloat(e.style.left),y:parseFloat(e.style.top),w:parseFloat(e.style.width),h:parseFloat(e.style.height),svgs:e.querySelectorAll('svg').length}))),total:window.__testApi.uiFacade._totalResultCount};});}
function oneCopy(state){assert.equal(state.hosts,1);assert.equal(state.surfaces,1);assert(state.parts.length>10);assert.equal(state.parts.length,state.total);assert.equal(new Set(state.parts.map(p=>p.id)).size,state.parts.length,'unique layout parts');for(const p of state.parts)assert.equal(p.svgs,1,'one image per layout part');for(let i=0;i<state.parts.length;i++)for(let j=0;j<i;j++){const a=state.parts[i],b=state.parts[j];assert(!(Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>.5 && Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>.5),'layout images must not overlap');}}
try{
 await page.goto(desktop?'guitario://app/':`http://127.0.0.1:${server.address().port}/`);await page.getByText('Start by adding your first guitar',{exact:true}).waitFor();
 await page.locator('#import-files').setInputFiles({name:'long.gp',mimeType:'application/octet-stream',buffer:bytes});await button('Import 1 song').click();await button('Open Long layout study').waitFor();
 await page.evaluate(()=>{const Native=window.alphaTab.AlphaTabApi;window.alphaTab.AlphaTabApi=new Proxy(Native,{construct(Target,args){const api=new Target(...args);window.__testApi=api;window.__testRenderCount=0;api.postRenderFinished.on(()=>window.__testRenderCount++);return api;}});});
 for(let cycle=0;cycle<4;cycle++){
  await button('Open Long layout study').click();await ready();const initial=await surfaces();console.log(JSON.stringify({cycle,parts:initial.parts.length,total:initial.total,duplicatePositions:initial.parts.filter((p,i,parts)=>parts.slice(0,i).some(q=>q.x===p.x && q.y===p.y)).length}));if(diagnose){await page.screenshot({path:`test-results/v101-before-${cycle}.png`,fullPage:true});}else oneCopy(initial);
  await button('Player settings').click();
  if(!diagnose){const slider=page.getByLabel('Notation spacing');assert.equal(await slider.getAttribute('step'),'0.01');assert(await slider.evaluate(el=>el.getBoundingClientRect().width<=170));const layouts={};for(const value of ['1.36','1.57','1.93','2.27','2.5','1.25']){const before=await page.evaluate(()=>window.__testRenderCount);await slider.fill(value);await page.waitForFunction(count=>window.__testRenderCount>count,before);await ready();assert.equal(await page.evaluate(()=>window.__testApi.settings.display.stretchForce),Number(value));const state=await surfaces();oneCopy(state);layouts[value]=JSON.stringify(state.parts.map(p=>[p.x,p.y,p.w,p.h]));}assert.notEqual(layouts['1.25'],layouts['2.5'],'spacing changes the actual score layout');
   const beforeRapid=await page.evaluate(()=>window.__testRenderCount);await page.evaluate(()=>{const slider=document.querySelector('[aria-label="Notation spacing"]'),set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;for(const value of [1.31,1.42,1.64,1.89,2.08,2.33]){set.call(slider,String(value));slider.dispatchEvent(new Event('input',{bubbles:true}));}});await page.waitForFunction(count=>window.__testRenderCount>count,beforeRapid);await page.waitForFunction(()=>window.__testApi.settings.display.stretchForce===2.33 && !document.querySelector('.loading-score'));oneCopy(await surfaces());
   for(const name of ['Both','Notation','Tab']){const before=await page.evaluate(()=>window.__testRenderCount);await button(name).click();await page.waitForFunction(count=>window.__testRenderCount>count,before);await ready();oneCopy(await surfaces());}
   assert.equal(await page.locator('.alpha-score').getByText('IMPORTED SECTION HEADING',{exact:false}).count(),0);assert((await page.locator('.alpha-score').innerText()).includes('P.M.'));assert.equal(await page.evaluate(()=>window.__testApi.score.masterBars[0].section.text),'IMPORTED SECTION HEADING');
  }
  await button('Player settings').click();await button('Return to library').click();
 }
 if(!diagnose){await button('Open Long layout study').click();await ready();await button('Edit IMPORTED SECTION HEADING').click();await page.getByLabel('Section name',{exact:true}).selectOption('Intro');await button('Save section').click();await page.locator('.score-section-label').getByText('Intro',{exact:true}).waitFor();assert(await page.evaluate(()=>{const glyphs=document.querySelector('.alpha-score'),tint=document.querySelector('.bar-overlay');return Number(getComputedStyle(glyphs).zIndex)>Number(getComputedStyle(tint).zIndex) && getComputedStyle(glyphs).pointerEvents==='none';}));
  assert(await page.evaluate(()=>{const label=document.querySelector('.score-section-label').getBoundingClientRect(),mute=[...document.querySelectorAll('.alpha-score text')].find(e=>e.textContent.includes('P.M.'))?.getBoundingClientRect();return !!mute && label.bottom+2<=mute.top;}),'section tag has its own space above palm muting');
  await page.locator('.score-paper').screenshot({path:'test-results/v101-score.png'});await button('Add recording').click();const choices=page.locator('.recording-choice');assert.equal(await choices.count(),2);assert(await button('Backing track').evaluate(el=>getComputedStyle(el).fontSize==='14px' && el.getBoundingClientRect().height>=36));await button('Backing track').click();assert.equal(await button('Backing track').getAttribute('aria-pressed'),'true');await button('YouTube link').click();assert.equal(await button('YouTube link').getAttribute('aria-pressed'),'true');await page.getByRole('dialog',{name:'Add recording',exact:true}).screenshot({path:'test-results/v101-recording.png'});await button('Close dialog').click();
  for(const [name,status] of [['Learning phrase','learning'],['Comfortable phrase','comfortable'],['Mastered phrase','mastered']]){await button('Update '+name+' progress').click();await page.getByLabel('Percentage learnt').fill(status==='learning'?'40':status==='comfortable'?'95':'100');await button('Save section').click();}
  async function progressVisible(){await page.mouse.move(0,0);for(const [name,status,title] of [['Intro','new','Not learnt'],['Learning phrase','learning','Learning · 40%'],['Comfortable phrase','comfortable','Comfortable'],['Mastered phrase','mastered','Mastered']]){const control=button('Update '+name+' progress');await control.locator('.status-mark.'+status).waitFor();assert.equal(await control.evaluate(el=>getComputedStyle(el).opacity),'1','section progress remains visible without hover');assert.equal(await control.locator('.status-mark').getAttribute('aria-label'),title);assert(await control.locator('svg').isVisible());}assert.equal(await button('Update Learning phrase progress').locator('.status-mark').innerText(),'40%');}
  await progressVisible();await page.locator('.sections-panel').screenshot({path:'test-results/section-progress.png'});await page.reload();await button('Open Long layout study').click();await ready();await progressVisible();
 }
 assert.deepEqual(errors,[]);console.log(`PASS: ${desktop?'Windows':'Edge'} ${diagnose?'diagnostic':'v'+version} long-score reopen, continuous spacing, single-copy render, marker visibility, overlay layers, recording selectors and persistent section progress (including reload).`);
}catch(e){await page.screenshot({path:'test-results/v101-failure.png'}).catch(()=>{});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
