/** Independent lesson playback and compact section workflow, always isolated. */
import {chromium,_electron as electron} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {checkRecordingModalLayer} from './modal-layer-check.mjs';
import * as alphaTab from '@coderline/alphatab';
const version=JSON.parse(fs.readFileSync('package.json','utf8')).version,root=path.resolve('dist');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));fs.mkdirSync('test-results',{recursive:true});
const desktop=process.argv.includes('--desktop'),profile=desktop?fs.mkdtempSync(path.resolve('test-results/desktop-v11-')):undefined;
const browser=desktop?await electron.launch({executablePath:process.env.GUITARIO_DESKTOP_EXECUTABLE || path.resolve(`../../Guitar-io-${version}-Windows-x64/Guitar.io.exe`),env:{...process.env,GUITARIO_TEST_PROFILE:profile}}):await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=desktop?await browser.firstWindow():await browser.newPage({viewport:{width:1512,height:960}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{
 localStorage.setItem('guitario-auto-artwork','off');window.__videos=[];
 window.YT={Player:class{
  constructor(_mount,options){this.time=0;this.state=2;this.rate=1;this.vol=75;this.options=options;window.__videos.push(this);queueMicrotask(()=>options.events.onReady({target:this}));}
  getCurrentTime(){return this.time;}getDuration(){return 400;}getPlayerState(){return this.state;}getAvailablePlaybackRates(){return [.25,.5,.75,1,1.25,1.5,2];}getPlaybackRate(){return this.rate;}setPlaybackRate(v){this.rate=v;this.options.events.onPlaybackRateChange?.({data:v});}getVolume(){return this.vol;}setVolume(v){this.vol=v;}seekTo(v){this.time=v;}playVideo(){this.state=1;}pauseVideo(){this.state=2;}destroy(){this.getCurrentTime=undefined;this.state=2;}
 }};
});
const button=name=>page.getByRole('button',{name,exact:true});
const score=alphaTab.importer.ScoreLoader.loadAlphaTex('\u005c\u005ctitle "Lesson study" \u005c\u005cartist "Original test" \u005c\u005ctuning C4 G3 Eb3 Bb2 F2 C2 . '+Array.from({length:16},()=>'(0.6 2.5).4 2.4.4 3.3.4 5.2.4').join(' | '));
for(const [index,name] of [[0,'Intro'],[4,'Verse'],[8,'Verse'],[12,'Chorus']]){const section=new alphaTab.model.Section();section.text=name;score.masterBars[index].section=section;}
const bytes=Buffer.from(new alphaTab.exporter.Gp7Exporter().export(score));
async function ready(){await button('Select bar 16').waitFor();await page.waitForFunction(()=>!document.querySelector('.loading-score'));}
async function stored(){return page.evaluate(async()=>{const db=await new Promise(resolve=>{const q=indexedDB.open('guitar-io-v1');q.onsuccess=()=>resolve(q.result);});return new Promise(resolve=>{const q=db.transaction('songs').objectStore('songs').getAll();q.onsuccess=()=>{db.close();resolve(q.result[0]);};});});}
try{
 await page.goto(desktop?'guitario://app/':`http://127.0.0.1:${server.address().port}/`);await page.getByText('Start by adding your first guitar',{exact:true}).waitFor();
 await page.locator('#import-files').setInputFiles({name:'lesson.gp',mimeType:'application/octet-stream',buffer:bytes});await button('Import 1 song').click();await button('Open Lesson study').waitFor();
 for(const view of ['Large cards','Small cards','List view']){await button(view).click();assert.equal(await page.getByRole('img',{name:'No guitar assigned to Lesson study',exact:true}).count(),1);assert(await page.getByRole('img',{name:'No guitar assigned to Lesson study',exact:true}).isVisible());await page.screenshot({path:`test-results/v11-library-${view.split(' ')[0]}.png`});}
 await button('Tunings').click();assert.equal(await page.getByRole('img',{name:'No guitar assigned to C standard',exact:true}).count(),1);await button('All songs').click();
 await page.evaluate(()=>{const Native=window.alphaTab.AlphaTabApi;window.alphaTab.AlphaTabApi=new Proxy(Native,{construct(Target,args){const api=new Target(...args);window.__testApi=api;return api;}});});
 await button('Open Lesson study').click();await ready();await checkRecordingModalLayer(page);await button('Edit Verse 1').click();assert.equal(await page.getByLabel('Section name').evaluate(el=>el.tagName),'SELECT');assert.equal(await page.getByLabel('From bar').getAttribute('type'),'range');assert.equal(await page.getByLabel('To bar').getAttribute('type'),'range');assert.equal(await page.getByLabel('Practice notes').count(),0);assert.equal(await page.getByLabel('Learning status').count(),0);
 await page.getByLabel('From bar').press('ArrowRight');assert.equal(await page.getByLabel('From bar').inputValue(),'6');await page.getByLabel('From bar').press('ArrowLeft');assert.equal(await page.getByLabel('From bar').inputValue(),'5');
 await page.getByLabel('To bar').press('ArrowLeft');assert.equal(await page.getByLabel('To bar').inputValue(),'7');await page.getByLabel('To bar').press('ArrowRight');assert.equal(await page.getByLabel('To bar').inputValue(),'8');
 const rangeBox=await page.locator('.bar-range').boundingBox();await page.mouse.move(rangeBox.x+9+(rangeBox.width-18)*10/15,rangeBox.y+rangeBox.height/2);await page.mouse.down();await page.mouse.move(rangeBox.x+9+(rangeBox.width-18)*6/15,rangeBox.y+rangeBox.height/2,{steps:4});await page.mouse.up();assert.equal(await page.getByLabel('To bar').inputValue(),'7');await page.getByLabel('To bar').press('ArrowRight');
 for(const [value,status] of [['0','new'],['1','learning'],['89','learning'],['90','comfortable'],['99','comfortable'],['100','mastered']]){await page.getByLabel('Percentage learnt').fill(value);await page.locator('.section-learning-control .status-mark.'+status).waitFor();}
 await page.getByLabel('Percentage learnt').fill('95');await page.getByLabel('Section name').selectOption('Pre-chorus');await button('Save section').click();await button('Edit Pre-chorus').waitFor();await button('Edit Verse').waitFor();assert.equal((await stored()).sectionsByTrack['0'].find(s=>s.start===5).learnedPercent,95);
 await button('Add recording').click();await button('Instructional video').click();assert.equal(await button('MP3').count(),0);assert.equal(await page.getByLabel('Attach MP3').count(),0);await page.getByLabel('YouTube video link').fill('https://www.youtube.com/watch?v=abcdefghijk');await button('Add recording').last().click();await button('Play instructional video').waitFor();assert.equal(await page.getByRole('tab',{name:'Instructional video',exact:true}).getAttribute('aria-selected'),'true');assert.equal(await button('Play').count(),0);
 const clock=await page.evaluate(()=>({tick:window.__testApi.tickPosition,speed:window.__testApi.playbackSpeed,mode:window.__testApi.settings.player.playerMode}));
 await page.getByLabel('Scrub instructional video').fill('250');await page.getByLabel('Instructional playback speed').selectOption('0.5');await button('Play instructional video').click();await button('Pause instructional video').waitFor();await page.locator('.song-heading h1').click();await page.keyboard.press('Space');await button('Play instructional video').waitFor();assert.deepEqual(await page.evaluate(()=>({tick:window.__testApi.tickPosition,speed:window.__testApi.playbackSpeed,mode:window.__testApi.settings.player.playerMode})),clock,'lesson playback never drives MIDI clock/speed/mode');
 await button('Edit Pre-chorus').click();await page.getByLabel('Timestamp in instructional').fill('2:05');await button('Save section').click();const lesson=(await stored()).media.recordings[0];assert.equal((await stored()).sectionsByTrack['0'].find(s=>s.start===5).instructionalTimestamps[lesson.id],125);
 await page.locator('.section-select').filter({hasText:'Pre-chorus'}).click();await page.waitForFunction(()=>window.__videos.at(-1).time===125);await page.locator('.sections-panel').screenshot({path:'test-results/v11-sections.png'});
 await button('Edit Pre-chorus').click();await page.locator('.section-editor').screenshot({path:'test-results/v11-section-editor.png'});await button('Cancel section edit').click();await page.locator('.integrated-player').screenshot({path:'test-results/v11-instructional.png'});
 await page.getByRole('tab',{name:'MIDI',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[aria-label="Play"]')?.disabled);assert.equal(await page.locator('.alpha-score').count(),1);
 await button('Select bar 6').click();await button('Select bar 10').click({modifiers:['Shift']});await button('Select bar 8').click({button:'right',position:{x:10,y:10}});await page.getByRole('menuitem',{name:'Merge selection',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.section-card').length===5);assert.deepEqual((await stored()).sectionsByTrack['0'].map(s=>[s.start,s.end]),[[1,4],[5,5],[6,10],[11,12],[13,16]]);await button('Undo notation edit').click();await page.waitForFunction(()=>document.querySelectorAll('.section-card').length===4);
 for(const count of [7,8]){await button('Change instrument tuning').click();await button(`${count} strings`).click();await button('Apply tuning').click();await ready();assert.equal((await stored()).tracks[0].strings,count);}
 await button('Change instrument tuning').click();await page.getByRole('dialog',{name:'Change instrument tuning'}).screenshot({path:'test-results/v11-string-count.png'});await button('Restore original tuning').click();await ready();assert.equal((await stored()).tracks[0].strings,6);
 await button('Return to library').click();await button('Guitars').click();await button('Add guitar').click();await page.getByLabel('Guitar name').fill('C guitar');await button('Add tuning').click();await button('STANDARD').click();await page.getByLabel('Tuning preset').selectOption('guitar-6-Standard--4');await button('Use this tuning').click();await button('Save guitar').click();await button('Tunings').click();assert.equal(await page.getByRole('img',{name:'No guitar assigned to C standard',exact:true}).count(),0);await button('All songs').click();assert.equal(await page.getByRole('img',{name:'No guitar assigned to Lesson study',exact:true}).count(),0);
 await page.reload();await button('Open Lesson study').click();await ready();await page.getByRole('tab',{name:'Instructional video',exact:true}).click();await button('Play instructional video').waitFor();await page.locator('.section-select').filter({hasText:'Pre-chorus'}).click();await page.waitForFunction(()=>window.__videos.at(-1).time===125);await button('Edit recording Instructional video').click();assert.equal(await page.getByLabel('Recording start offset').count(),0);await button('Close dialog').click();await page.getByRole('tab',{name:'MIDI',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[aria-label="Play"]')?.disabled);
 await button('Add recording').click();await button('Instructional video').click();await page.getByLabel('YouTube video link').fill('https://www.youtube.com/watch?v=lmnopqrstuv');await button('Add recording').last().click();await button('Play instructional video').waitFor();const second=(await stored()).media.recordings.find(r=>r.id!==lesson.id);await button('Edit Pre-chorus').click();assert.equal(await page.getByLabel('Section instructional video').inputValue(),second.id);await page.getByLabel('Timestamp in instructional').fill('3:10');await page.getByLabel('Section instructional video').selectOption(lesson.id);assert.equal(await page.getByLabel('Timestamp in instructional').inputValue(),'2:05');await button('Save section').click();assert.deepEqual((await stored()).sectionsByTrack['0'].find(s=>s.start===5).instructionalTimestamps,{[lesson.id]:125,[second.id]:190});await page.locator('.section-select').filter({hasText:'Pre-chorus'}).click();await page.waitForFunction(()=>window.__videos.at(-1).time===190);await button('Edit recording '+second.label).click();await button('Remove').click();await button('Remove recording').click();await page.waitForFunction(()=>!document.querySelector('[aria-label="Play"]')?.disabled);assert.deepEqual((await stored()).sectionsByTrack['0'].find(s=>s.start===5).instructionalTimestamps,{[lesson.id]:125});
 assert.deepEqual(errors,[]);console.log(`PASS ${desktop?'Windows':'Edge'} ${version}: instructional independence/timestamps/reload, compact sections/range/progress/name numbering, merge/undo, 6/7/8 strings/restore, missing-guitar indicators and MIDI return.`);
}catch(e){await page.screenshot({path:'test-results/v11-failure.png'}).catch(()=>{});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));if(profile){assert(profile.startsWith(path.resolve('test-results')+path.sep));fs.rmSync(profile,{recursive:true,force:true});}}
