import {chromium,_electron as electron} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {serve,fixtures,seed,capturePlayer,instrument} from './library-harness.mjs';

const desktop=process.argv.includes('--desktop'),profile=desktop?fs.mkdtempSync(path.resolve('test-results/desktop-v122-')):undefined;
const server=await serve('dist'),version=JSON.parse(fs.readFileSync('package.json')).version;
const browser=desktop?await electron.launch({executablePath:path.resolve(process.env.GUITARIO_OUTPUT_DIR || 'release/artifacts',`Guitar-io-${version}-Windows-x64/Guitar.io.exe`),env:{...process.env,GUITARIO_TEST_PROFILE:profile}}):await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const context=desktop?browser.context():await browser.newContext({viewport:{width:1512,height:960}}),page=desktop?await browser.firstWindow():await context.newPage(),url=desktop?'guitario://app/':server.url,errors=[];
const button=name=>page.getByRole('button',{name,exact:true});page.on('pageerror',e=>errors.push(e.message));
const songs=fixtures(12,16);songs.forEach((s,i)=>{s.lastPlayedAt=new Date(Date.UTC(2026,9,3,0,i)).toISOString();});
const section=(id,start,end,status,learnedPercent)=>({id,name:id,start,end,status,learnedPercent,notes:'',color:'#8b79ff'});
const selected=songs[11];selected.tuning='Drop C';selected.tracks[0].tuning='Drop C';selected.tracks[0].notes='C2 · G2 · C3 · F3 · A3 · D4';selected.tuningEdits={'0:0':[62,57,53,48,43,36]};selected.guitars=['Retuned test guitar'];selected.tempoEdits={'1':85};selected.bpm=85;
selected.sections=selected.sectionsByTrack['0']=[section('Intro',1,4,'new',0),section('Verse',5,8,'learning',50),section('Chorus',9,12,'comfortable',95),section('Outro',13,16,'mastered',100)];
songs[10].sections=songs[10].sectionsByTrack['0']=[section('Complete',1,16,'mastered',100)];
songs[9].sections=songs[9].sectionsByTrack['0']=[section('Almost',1,15,'mastered',100),section('Final bar',16,16,'comfortable',99)];
selected.media={recordings:[{id:'old-match',kind:'youtube',videoId:'dQw4w9WgXcQ',url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',offsetSeconds:12.5,label:'Full song',purpose:'full',tags:[],tempo:{bpm:100,referenceBpm:85,method:'manual'},syncAnchors:[{scoreSeconds:0,mediaSeconds:10},{scoreSeconds:20,mediaSeconds:34}]}]};
function card(title){return page.locator('.song-card').filter({has:page.getByRole('heading',{name:title,exact:true})});}
async function split(rail){await rail.scrollIntoViewIfNeeded();const parts=await rail.locator('i').evaluateAll(nodes=>nodes.map(n=>({state:n.dataset.status,width:n.style.width,colour:getComputedStyle(n).backgroundColor,rect:n.getBoundingClientRect().width})));assert.deepEqual(parts.map(p=>p.state),['mastered','comfortable','learning','new']);assert.deepEqual(parts.map(p=>p.width),['25%','25%','25%','25%']);assert.equal(new Set(parts.map(p=>p.colour)).size,4);assert.equal(parts[2].colour,'rgb(220, 161, 106)');assert(parts.every(p=>p.rect>0),JSON.stringify(parts));}
try{
  await instrument(page);
  if(desktop)await page.getByText('Start by adding your first guitar',{exact:true}).waitFor();await seed(page,url,songs,desktop);await page.goto(url);await button('Preview Synthetic study 011').waitFor();await page.reload();await button('Preview Synthetic study 011').waitFor();
  const io=await page.evaluate(()=>window.__io);assert.equal(io['songSources.get'] || 0,0);assert.equal(io['songs.get'] || 0,0);
  assert.equal(await page.locator('.recent-story').count(),10);
  for(const view of ['Large cards','Small cards','List view']){await button(view).click();await split(card(selected.title).locator('.song-progress-rail'));assert.equal(await card(songs[10].title).getByRole('img',{name:`${songs[10].title} fully mastered`,exact:true}).count(),1);assert.equal(await card(songs[9].title).getByRole('img',{name:`${songs[9].title} fully mastered`,exact:true}).count(),0);assert((await card(songs[9].title).textContent()).includes('100% learnt'));}
  await button('Large cards').click();await page.screenshot({path:'test-results/v122-library.png'});
  await button('Preview Synthetic study 011').click();const story=page.getByRole('dialog');await story.getByText('Drop C | Retuned test guitar',{exact:true}).waitFor();await page.waitForFunction(()=>Number(document.querySelector('[aria-label="Preview progress"]')?.getAttribute('aria-valuenow'))>0);
  assert(!(await story.textContent()).includes('Your progress'));assert(!(await story.textContent()).includes('BPM'));assert(!(await story.textContent()).includes(selected.album));await split(story.locator('.song-progress-rail'));await story.locator('.song-progress-rail').hover();const tooltip=page.getByRole('tooltip');await tooltip.waitFor();assert.deepEqual(await tooltip.locator('span').allTextContents(),['Mastered','Learnt','Learning','Not attempted yet']);assert.deepEqual(await tooltip.locator('strong').allTextContents(),['25%','25%','25%','25%']);await page.screenshot({path:'test-results/v122-story.png'});await page.mouse.move(10,10);await tooltip.waitFor({state:'detached'});
  if(!desktop){await page.setViewportSize({width:390,height:844});const bounds=await page.locator('.story-music-meta').boundingBox();assert(bounds.width<390);assert(await page.locator('.story-music-meta').evaluate(el=>getComputedStyle(el).whiteSpace==='nowrap'));await page.setViewportSize({width:1512,height:960});}
  await button('Next preview').click();await story.getByRole('img',{name:`${songs[10].title} fully mastered`,exact:true}).waitFor();await button('Close dialog').click();
  await button(`Edit ${selected.title} details`).click();await page.getByRole('dialog',{name:'Song details',exact:true}).waitFor();const icons=page.locator('.artwork-icon-actions');assert.equal(await icons.locator('button').count(),3);assert.equal((await icons.textContent()).trim(),'');assert(await icons.locator('button').evaluateAll(nodes=>nodes.every(n=>getComputedStyle(n).borderTopWidth==='0px' && Number(n.querySelector('svg').getAttribute('width'))>=28)));
  await page.screenshot({path:'test-results/v122-artwork.png'});await button('Remove artwork').click();assert.equal(await page.getByAltText('Selected album artwork').count(),0);
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');await page.getByLabel('Upload artwork',{exact:true}).setInputFiles({name:'test-cover.png',mimeType:'image/png',buffer:png});await page.getByAltText('Selected album artwork').waitFor();await button('Save changes').click();
  await capturePlayer(page);await button(`Open ${selected.title}`).click();await button('Select bar 16').waitFor();await page.waitForFunction(()=>window.__testApi?.isReadyForPlayback);
  assert.equal(await button('Edit song tempo').count(),0);assert.equal(await page.locator('.tempo-editor').count(),0);await button('Player settings').click();await page.getByLabel('Song default BPM').waitFor();assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await button('Add tempo change').getAttribute('title'),'Add tempo change');
  await page.getByLabel('Song default BPM').fill('95');await button('Add tempo change').click();await page.getByLabel('Tempo starting bar 1').fill('9');await page.getByLabel('Bar tempo BPM 1').fill('140');await button('Save song tempo').click();await page.waitForFunction(()=>window.__testApi.score.tempo===95 && window.__testApi.score.masterBars[8].tempoAutomations[0].value===140);
  await page.getByLabel('Bar tempo BPM 1').fill('130');await button('Save song tempo').click();await page.waitForFunction(()=>window.__testApi.score.masterBars[8].tempoAutomations[0].value===130);await button('Undo notation edit').click();await page.waitForFunction(()=>window.__testApi.score.masterBars[8].tempoAutomations[0].value===140);await button('Undo notation edit').click();await page.waitForFunction(()=>window.__testApi.score.tempo===85);
  await page.screenshot({path:'test-results/v122-tempo.png'});await button('Player settings').click();assert.equal(await page.locator('.tempo-editor').count(),0);
  await page.evaluate(()=>{window.YT={Player:class{constructor(_el,o){this.time=0;this.rate=1;this.state=2;this.o=o;window.__video=this;queueMicrotask(()=>o.events.onReady({target:this}));}getCurrentTime(){return this.time;}getDuration(){return 400;}getPlayerState(){return this.state;}getPlaybackRate(){return this.rate;}getAvailablePlaybackRates(){return [.25,.5,.75,1];}setPlaybackRate(r){this.rate=r;this.o.events.onPlaybackRateChange({data:r});}getVolume(){return 75;}setVolume(){}seekTo(s){this.time=s;}playVideo(){this.state=1;}pauseVideo(){this.state=2;}destroy(){this.state=2;}}};});
  await page.getByRole('tab',{name:'Full song',exact:true}).click();await button('Edit recording Full song').click();await page.getByText('Offset (seconds)',{exact:true}).waitFor();assert(!/Match recording tempo|Fine timing adjustments|analy[sz]|Recording BPM/i.test(await page.getByRole('dialog').textContent()));await page.getByLabel('Recording start offset').fill('10');await button('Save recording').click();await page.waitForFunction(()=>window.__testApi.player.output.handler);await button('Select bar 5').click();await page.waitForFunction(()=>Math.abs(window.__video.time-(10+960/85))<.12);
  assert.equal(await page.locator('.recording-tempo-status').count(),0);if(desktop)assert(await page.evaluate(()=>!window.guitarIO.prepareTempoCapture));
  await page.getByRole('tab',{name:'MIDI',exact:true}).click();await page.waitForFunction(()=>window.__testApi.settings.player.playerMode===window.alphaTab.PlayerMode.EnabledSynthesizer);assert.equal(await page.evaluate(()=>window.__testApi.score.tempo),85);
  await button('Return to library').click();await page.reload();await button(`Open ${selected.title}`).click();await button('Select bar 16').waitFor();await button('Player settings').click();assert.equal(await page.getByLabel('Song default BPM').inputValue(),'85');
  assert.deepEqual(errors,[]);console.log(`PASS v1.2.2 ${desktop?'Windows':'browser'}: split progress/mastery in all views and Stories, compact story metadata, artwork icons/upload/remove, inline tempo rows/save/undo/reload, offset-only recordings and inactive legacy calibration, lazy startup.`);
}finally{
  if(!desktop)await context.close();await browser.close();await server.close();if(profile){assert(profile.startsWith(path.resolve('test-results')+path.sep));fs.rmSync(profile,{recursive:true,force:true});}
}
