import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {serve,seed,fixtures,capturePlayer} from './library-harness.mjs';
const server=await serve('dist'),browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const context=await browser.newContext({viewport:{width:1512,height:960}}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));const button=name=>page.getByRole('button',{name,exact:true});
const song=fixtures(1,16)[0];song.sections=song.sectionsByTrack['0']=[{id:'verse',name:'Verse',start:1,end:16,color:'#24b8a8',status:'learning',learnedPercent:40,notes:'Verse notes'}];
song.media={recordings:[{id:'video',label:'Full song',kind:'youtube',purpose:'full',tags:[],offsetSeconds:4,videoId:'dQw4w9WgXcQ',youtubeSync:{enabled:true,source:'manual',videoId:'dQw4w9WgXcQ',points:[{bar:1,seconds:4},{bar:9,seconds:20},{bar:16,seconds:34}]}}]};
try{
  await page.goto(server.url);await seed(page,server.url,[song],true);await page.goto(server.url);await button(`Open ${song.title}`).waitFor();await capturePlayer(page);await button(`Open ${song.title}`).click();await button('Select bar 16').waitFor();await page.waitForFunction(()=>window.__testApi?.isReadyForPlayback);
  await button('Player settings').click();assert.equal(await page.locator('.zoom-control>span').textContent(),'100%');await button('Zoom in').click();assert.equal(await page.locator('.zoom-control>span').textContent(),'110%');assert.equal(await page.evaluate(()=>window.__testApi.settings.display.scale),1.1);await button('Reset zoom').click();assert.equal(await page.locator('.zoom-control>span').textContent(),'100%');
  assert.equal(await page.getByLabel('Song default BPM').count(),0);await button('Count in').click();await page.waitForFunction(()=>window.__testApi.countInVolume>0);
  await button('Speed display unit').click();await page.getByLabel('Playback BPM').fill('90');await page.getByLabel('Playback BPM').press('Enter');await page.waitForFunction(()=>window.__testApi.playbackSpeed===.75);
  const before=await page.locator('.score-column').evaluate(e=>e.clientWidth);await button('Collapse song sections').click();assert.equal(await page.locator('.sections-panel').isVisible(),false);assert(await page.locator('.score-column').evaluate(e=>e.clientWidth)>before);await button('Show song sections').click();
  await button('Select bar 7').click();await button('Select bar 10').click({modifiers:['Shift']});await button('Create section').click();const name=page.getByLabel('Section name',{exact:true});if(await name.count())await name.selectOption('Solo');else{await page.locator('.section-editor select').first().selectOption('Solo');}
  await button('Save section').click();await page.waitForFunction(()=>[...document.querySelectorAll('.section-select strong')].map(e=>e.textContent).join('|')==='Verse 1|Solo|Verse 2');
  await page.evaluate(()=>{window.YT={Player:class{constructor(el,o){this.time=0;this.rate=1;this.state=2;this.o=o;window.__video=this;const frame=document.createElement('iframe');frame.title='Controlled recording';el.replaceWith(frame);queueMicrotask(()=>o.events.onReady({target:this}));}getCurrentTime(){return this.time;}getDuration(){return 90;}getPlayerState(){return this.state;}getPlaybackRate(){return this.rate;}getAvailablePlaybackRates(){return [.5,1];}setPlaybackRate(r){this.rate=r;this.o.events.onPlaybackRateChange({data:r});}getVolume(){return 75;}setVolume(){}seekTo(s){this.time=s;}playVideo(){this.state=1;}pauseVideo(){this.state=2;}destroy(){this.state=2;}}};});
  await page.getByRole('tab',{name:'Full song',exact:true}).click();await page.waitForFunction(()=>window.__video && window.__testApi.player.output.handler);await page.getByLabel('Playback BPM').fill('70');await page.getByLabel('Playback BPM').press('Enter');await page.waitForFunction(()=>window.__testApi.playbackSpeed===.5 && window.__video.rate===.5);assert.equal(await page.getByLabel('Playback BPM').inputValue(),'60');
  await button('Play').click();await page.waitForFunction(()=>window.__video.state===1);await button('Minimize YouTube player').click();assert.equal(await page.evaluate(()=>window.__video.state),1);assert(await page.locator('.youtube-frame').evaluate(e=>e.getBoundingClientRect().right<0));await button('Show YouTube player').click();await button('Pause').click();
  await button('Edit recording Full song').click();assert.equal(await page.locator('.youtube-sync-editor').getAttribute('open'),null);await page.getByLabel('Recording offset in bars').fill('-2');await page.locator('.youtube-sync-editor summary').click();assert.equal(await page.getByLabel('Sync seconds 1').inputValue(),'-4');assert.equal(await page.getByLabel('Sync seconds 2').inputValue(),'12');await button('Save recording').click();await button('Select bar 9').click();await page.waitForFunction(()=>Math.abs(window.__video.time-12)<.01);
  await page.screenshot({path:'test-results/v141-player.png'});await button('Return to library').click();await button('Guitars').click();await button('Add guitar').click();await page.getByLabel('Guitar name').fill('Test guitar');await button('Save guitar').click();await button('Open Test guitar collection').click();await button('Add tunings').click();await button('STANDARD').click();await page.getByLabel('Tuning preset').selectOption({index:1});assert.equal(await button('Add tuning').locator('svg').count(),1);assert.equal(await button('Save guitar').evaluate(e=>getComputedStyle(e).cursor),'default');await button('Add tuning').click();await button('Save guitar').click();
  // All controls in dynamic menus receive tooltips; disabled controls use a normal cursor.
  await button('Device sync').click();await button('Close dialog').waitFor();assert(await button('Close dialog').getAttribute('title'));await button('Close dialog').click();
  await page.goto(server.url+'?learn=1');await page.getByRole('heading',{name:'Scales & modes'}).waitFor();await button('DROP').click();await page.getByLabel('Tuning preset').selectOption({index:1});assert.equal(await page.getByLabel('Learn tuning',{exact:true}).count(),0);assert(await button('Hear tuning').getAttribute('title'));await page.screenshot({path:'test-results/v141-learn.png'});
  await page.setViewportSize({width:393,height:852});await page.screenshot({path:'test-results/v141-learn-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);console.log('PASS V1.4.1 UI: 100% adjustable zoom, count-in, compact header, collapse/restore, overlap split, supported BPM rates, video minimization while playing, negative bar offset shifts every point, Learn tuning families, mobile layout, tooltips.');
}finally{await context.close();await browser.close();await server.close();}
