import { chromium, _electron as electron } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import * as alphaTab from '@coderline/alphatab';
const root = path.resolve('dist');
const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://localhost'), file = path.resolve(root, '.' + (url.pathname === '/' ? '/index.html' : url.pathname));
  if (!file.startsWith(root + path.sep) || !fs.existsSync(file)) { res.writeHead(404); res.end(); return; }
  res.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.mjs': 'text/javascript', '.woff2': 'font/woff2' })[path.extname(file)] || 'application/octet-stream'); fs.createReadStream(file).pipe(res);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
fs.mkdirSync('test-results', { recursive: true });
const desktop = process.argv.includes('--desktop');
const { version } = JSON.parse(fs.readFileSync('package.json', 'utf8'));
const browser = desktop ? await electron.launch({ executablePath: path.resolve(`../../Guitar-io-${version}-Windows-x64/Guitar.io.exe`), env: { ...process.env, GUITARIO_TEST_PROFILE: fs.mkdtempSync(path.resolve('test-results/desktop-editing-')) } }) : await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const page = desktop ? await browser.firstWindow() : await browser.newPage({ viewport: { width: 1512, height: 960 } });
await page.addInitScript(() => localStorage.setItem('guitario-auto-artwork', 'off'));
const errors = []; page.on('pageerror', e => errors.push(e.message));
const button = name => page.getByRole('button', { name, exact: true });
const note = () => page.locator('.note-hit').nth(2);
const ready = () => page.waitForFunction(() => document.querySelectorAll('.bar-overlay').length === 4 && !document.querySelector('[aria-label="Play"]')?.disabled);
async function dialogClosed(name) { await page.getByRole('dialog', { name, exact: true }).waitFor({ state: 'detached' }); await ready(); }
async function menu(name) { await note().click({ button: 'right' }); await page.getByRole('menuitem', { name, exact: true }).click(); }
async function librarySong() { return page.evaluate(async () => { const db = await new Promise((resolve, reject) => { const req = indexedDB.open('guitar-io-v1'); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); return new Promise(resolve => { const request = db.transaction('songs').objectStore('songs').getAll(); request.onsuccess = () => { db.close(); resolve(request.result.find(s => s.title === 'Repeat loop study')); }; }); }); }
try {
  fs.mkdirSync('test-results', { recursive: true });
  await page.goto(desktop ? 'guitario://app/' : `http://127.0.0.1:${server.address().port}/`);
  await button('Open Afterglow').waitFor();
  await page.evaluate(() => { const Native = window.alphaTab.AlphaTabApi; window.alphaTab.AlphaTabApi = new Proxy(Native, { construct(Target, args) { const api = new Target(...args); window.__testApi = api; return api; } }); });
  const fixture = alphaTab.importer.ScoreLoader.loadAlphaTex('\\title "Repeat loop study" \\tempo 360 . 0.6.1 | 1.6.1 | 2.6.1 | 3.6.1');
  fixture.masterBars[0].isRepeatStart = true; fixture.masterBars[1].repeatCount = 2; fixture.rebuildRepeatGroups();
  await page.locator('#import-files').setInputFiles({ name: 'repeat-loop.gp', mimeType: 'application/octet-stream', buffer: Buffer.from(new alphaTab.exporter.Gp7Exporter().export(fixture)) });
  await page.getByRole('dialog', { name: 'Review import' }).waitFor(); await page.getByRole('button', { name: /^Import [0-9]+ songs?$/ }).click();
  await button('Open Repeat loop study').click(); await ready();
  assert.equal(await page.getByRole('spinbutton', { name: 'Loop start bar' }).count(), 0);
  await button('Loop selected bars').click();
  await page.getByRole('spinbutton', { name: 'Loop start bar' }).fill('2');
  await page.getByRole('spinbutton', { name: 'Loop end bar' }).fill('3');
  const loop = await page.evaluate(() => { const a = window.__testApi; return { range: a.playbackRange, looping: a.isLooping, bars: a.tickCache.masterBars.map(b => ({ bar: b.masterBar.index + 1, start: b.start, end: b.end })) }; });
  assert.equal(loop.looping, true);
  assert.deepEqual(loop.range, { startTick: loop.bars.filter(b => b.bar === 2).at(-1).start, endTick: loop.bars.find(b => b.bar === 3).end });
  await page.evaluate(() => { window.__played = []; window.__testApi.playedBeatChanged.on(beat => window.__played.push(beat.voice.bar.index + 1)); });
  await button('Loop selected bars').focus(); await page.keyboard.press('Space'); await button('Pause').waitFor();
  await page.waitForFunction(() => { const s = window.__played; return s.includes(3) && s.slice(s.indexOf(3) + 1).includes(2); }, { timeout: 10000 });
  await page.keyboard.press('Space'); await button('Play').waitFor();
  assert.equal(await button('Loop selected bars').getAttribute('aria-pressed'), 'true', 'Space must not toggle the focused loop button');
  await button('Loop selected bars').click();
  await button('Next bar').focus(); await page.keyboard.press('Space'); await button('Pause').waitFor(); await page.keyboard.press('Space');
  console.log('PASS: a real repeated score loops through bars 2 and 3, then back to 2; Space controls playback with transport buttons focused.');

  await button('Select bar 1').click({position:{x:12,y:12}});
  await button('Create section').click();
  await page.getByRole('textbox', { name: 'Section name', exact: true }).fill('Phrase');
  await page.getByRole('textbox', { name: 'Practice notes', exact: true }).fill('test');
  await page.getByRole('textbox', { name: 'Practice notes', exact: true }).press('Space');
  assert.equal(await button('Pause').count(), 0, 'Typing spaces must not start playback');
  await button('Save section').click();
  const annotation = page.locator('.sheet-annotation').filter({ hasText: 'test' });
  await annotation.waitFor();
  const beforePosition = await annotation.boundingBox();
  const handle = await button('Move Phrase annotation').boundingBox();
  await page.mouse.move(handle.x + 30, handle.y + 8); await page.mouse.down(); await page.mouse.move(handle.x + 120, handle.y + 55, { steps: 5 }); await page.mouse.up();
  await page.waitForFunction(before => Math.abs(document.querySelector('.sheet-annotation').getBoundingClientRect().x - before.x - 90) < 3, beforePosition);
  const afterPosition = await annotation.boundingBox();
  assert(Math.abs(afterPosition.x - beforePosition.x - 90) < 3);
  await button('Edit Phrase annotation').click();
  await page.getByRole('textbox', { name: 'Annotation text' }).fill('test — movable text');
  await button('Save annotation').click(); await dialogClosed('Sheet annotation');
  assert((await librarySong()).annotationPositions);
  console.log('PASS: existing section notes appear on the sheet, move with a drag and edit as text.');

  assert.equal(await button('Select notes').count(), 0);
  await note().waitFor();
  assert.equal(await page.locator('.note-hit').count(), 4);
  await menu('Edit fret / string');
  await page.getByRole('spinbutton', { name: 'Note fret' }).fill('5');
  await button('Apply notation edit').click(); await dialogClosed('Edit note');
  assert.match(await note().getAttribute('aria-label'), /fret 5/);
  await menu('Annotate note');
  await page.getByRole('textbox', { name: 'Annotation text' }).fill('Let this note ring');
  await button('Save annotation').click(); await dialogClosed('Sheet annotation');
  await page.locator('.annotation-text').filter({ hasText: 'Let this note ring' }).waitFor();
  await menu('Transpose selected notes');
  await page.getByRole('spinbutton', { name: 'Transpose semitones' }).fill('');
  await page.getByRole('spinbutton', { name: 'Transpose semitones' }).pressSequentially('-2');
  assert.equal(await page.getByRole('spinbutton', { name: 'Transpose semitones' }).inputValue(), '-2');
  await page.getByRole('spinbutton', { name: 'Transpose semitones' }).fill('2');
  await button('Apply notation edit').click(); await dialogClosed('Transpose / tuning');
  assert.match(await note().getAttribute('aria-label'), /fret 7/);
  const pitch = await page.evaluate(() => window.__testApi.score.tracks[0].staves[0].bars[2].voices[0].beats[0].notes[0].realValue);
  await menu('Suggest alternate fingerings');
  await page.getByRole('spinbutton', { name: 'Highest fret' }).fill('4');
  await button('Preview fingerings').click();
  await page.getByText('1 note will move.', { exact: true }).waitFor();
  await page.screenshot({ path: 'test-results/v5-fingering.png' });
  await button('Apply notation edit').click(); await dialogClosed('Alternate fingerings');
  const shifted = await page.evaluate(() => { const n = window.__testApi.score.tracks[0].staves[0].bars[2].voices[0].beats[0].notes[0]; return { pitch: n.realValue, fret: n.fret, string: n.string }; });
  assert.equal(shifted.pitch, pitch); assert.equal(shifted.fret, 2); assert.equal(shifted.string, 2);
  await button('Player settings').click();
  await button('Undo notation edit').click(); await ready();
  await page.waitForFunction(() => document.querySelectorAll('.note-hit')[2]?.getAttribute('aria-label').includes('fret 7'));
  await button('Undo notation edit').click(); await ready();
  await page.waitForFunction(() => document.querySelectorAll('.note-hit')[2]?.getAttribute('aria-label').includes('fret 5'));
  await button('Transpose / tuning').click();
  await page.getByRole('combobox', { name: 'Pitch or tuning' }).selectOption('tuning');
  await button('DROP').click(); await page.getByRole('combobox', { name: 'Tuning preset' }).selectOption('guitar-6-Drop-0');
  await button('Apply notation edit').click(); await dialogClosed('Transpose / tuning');
  assert.match(await note().getAttribute('aria-label'), /fret 7/);
  await page.screenshot({ path: 'test-results/v5-annotations-notes.png' });
  await button('Player settings').click();
  // Direct number entry must survive a score rerender between digits.
  await note().click(); await page.keyboard.press('1'); await page.keyboard.press('1');
  await page.waitForFunction(() => document.querySelectorAll('.note-hit')[2]?.getAttribute('aria-label').includes('fret 11'));
  await new Promise(resolve => setTimeout(resolve, 1100)); await page.keyboard.press('2');
  await page.waitForFunction(() => document.querySelectorAll('.note-hit')[2]?.getAttribute('aria-label').includes('fret 2'));
  await page.locator('.note-hit').nth(3).click({modifiers:['Shift']});
  assert.equal(await page.locator('.note-hit.selected').count(), 2);
  await page.keyboard.press('7');
  await page.waitForFunction(() => [...document.querySelectorAll('.note-hit')].slice(2).every(n => n.getAttribute('aria-label').includes('fret 7')));
  assert.equal(await page.locator('.note-hit.selected').count(), 2);
  console.log('PASS: direct note selection, multi-note fret entry and one-second digit reset survive rendering.');
  await button('Player settings').click();
  const saved = await librarySong();
  if (desktop) {
    await browser.evaluate(({ session }, target) => { globalThis.__testDownloadState = null; session.defaultSession.once('will-download', (_event, item) => { item.setSavePath(target); item.once('done', (_event, state) => { globalThis.__testDownloadState = state; }); }); }, path.resolve('test-results/v5-edited.gp'));
    await button('Export edited GP').click();
    let state;
    for (let i = 0; i < 100; i++) { state = await browser.evaluate(() => globalThis.__testDownloadState); if (state) break; await new Promise(resolve => setTimeout(resolve, 100)); }
    assert.equal(state, 'completed', 'The Windows GP export must complete');
  } else {
    const gpDownload = page.waitForEvent('download'); await button('Export edited GP').click(); await (await gpDownload).saveAs('test-results/v5-edited.gp');
  }
  const exported = alphaTab.importer.ScoreLoader.loadScoreFromBytes(new Uint8Array(fs.readFileSync('test-results/v5-edited.gp')));
  assert.equal(exported.tracks[0].staves[0].bars[2].voices[0].beats[0].notes[0].fret, 7);
  assert.match(exported.tracks[0].staves[0].bars[2].voices[0].beats[0].text, /Let this note ring/);
  assert.match(exported.tracks[0].staves[0].bars[0].voices[0].beats[0].text, /test — movable text/);
  await button('Your library').click(); await page.reload();
  await button('Open Afterglow').waitFor();
  await page.evaluate(() => { const Native = window.alphaTab.AlphaTabApi; window.alphaTab.AlphaTabApi = new Proxy(Native, { construct(Target,args) { const api = new Target(...args); window.__testApi = api; return api; } }); });
  await button('Open Repeat loop study').click(); await ready();
  await page.locator('.annotation-text').filter({ hasText: 'test — movable text' }).waitFor();
  await page.locator('.annotation-text').filter({ hasText: 'Let this note ring' }).waitFor();
  const reloaded = await librarySong();
  assert.deepEqual(reloaded.noteEdits, saved.noteEdits); assert.deepEqual(reloaded.tuningEdits, saved.tuningEdits); assert.deepEqual(reloaded.annotationPositions, saved.annotationPositions);
  await page.setViewportSize({ width: 1100, height: 760 });
  await page.screenshot({ path: 'test-results/v5-small-window.png' });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.setViewportSize({width:1512,height:960});
  await button('Player settings').click();
  await button('Transpose / tuning').click();
  await page.getByRole('combobox', {name:'Pitch or tuning'}).selectOption('tuning');
  await button('DROP').click(); await page.getByRole('combobox', {name:'Tuning preset'}).selectOption('guitar-6-Drop--3');
  await button('Apply notation edit').click(); await dialogClosed('Transpose / tuning');
  const beforeBb = await page.evaluate(() => window.__testApi.score.tracks[0].staves[0].bars.flatMap(b => b.voices.flatMap(v => v.beats.flatMap(b => b.notes))).map(n => ({fret:n.fret,string:n.string,pitch:n.realValue})));
  await button('Transpose / tuning').click();
  await page.getByRole('combobox', {name:'Pitch or tuning'}).selectOption('tuning');
  await button('DROP').click(); await page.getByRole('combobox', {name:'Tuning preset'}).selectOption('guitar-6-Drop--4');
  await button('Apply notation edit').click(); await dialogClosed('Transpose / tuning');
  const afterBb = await page.evaluate(() => window.__testApi.score.tracks[0].staves[0].bars.flatMap(b => b.voices.flatMap(v => v.beats.flatMap(b => b.notes))).map(n => ({fret:n.fret,string:n.string,pitch:n.realValue})));
  assert.deepEqual(afterBb, beforeBb.map(n => ({...n,fret:n.fret+1})));
  await button('Transpose / tuning').click();
  await page.getByRole('spinbutton', {name:'Transpose semitones'}).fill('-24');
  await button('Apply notation edit').click(); await dialogClosed('Transpose / tuning');
  assert.equal(await page.locator('.invalid-note').count(), 4);
  assert(await page.locator('.alpha-score').evaluate(n => n.innerHTML.toLowerCase().includes('#d22830')));
  await page.screenshot({path:'test-results/v5-red-notes.png'});
  await button('Undo notation edit').click();
  await page.waitForFunction(() => !document.querySelector('.invalid-note'));
  await button('Transpose / tuning').click();
  await page.getByRole('combobox', {name:'Pitch or tuning'}).selectOption('tuning');
  await button('CUSTOM').click();
  await page.getByRole('combobox', {name:'String 6 note',exact:true}).selectOption('11');
  assert.equal(await page.getByRole('combobox', {name:'String 6 octave',exact:true}).inputValue(),'1');
  await page.screenshot({path:'test-results/v5-headstock.png'});
  await button('Cancel').click();
  console.log('PASS: Drop B to Drop Bb adds one fret on every original string; invalid frets render red without blocking; visual custom tuning editor works.');
  // Library guitar profiles and tuning drill-down.
  await button('Your library').click(); await button('Guitars').click();
  await button('Add guitar').click();
  await page.getByRole('textbox',{name:'Guitar name',exact:true}).fill('ESP test');
  await page.getByRole('textbox',{name:'Make',exact:true}).fill('ESP');
  await page.getByRole('textbox',{name:'Model',exact:true}).fill('E-II');
  for (const preset of ['guitar-6-Drop--3','guitar-6-Standard--5','guitar-6-Drop--5','guitar-6-Drop--4']) {
    await button('Add tuning').click(); await button(preset.includes('Drop') ? 'DROP' : 'STANDARD').click(); await page.getByRole('combobox',{name:'Tuning preset'}).selectOption(preset); await button('Use this tuning').click();
  }
  await button('Save guitar').click(); await page.getByRole('dialog').waitFor({state:'detached'});
  await button('Open ESP test collection').click();
  await button('Open Drop B collection').waitFor(); await button('Open Drop A collection').waitFor();
  await button('Open Drop B collection').click(); assert.equal(await page.locator('.song-card').count(),0);
  await page.reload(); await button('Guitars').click(); await button('Edit guitar ESP test').click();
  assert.equal(await page.getByRole('textbox',{name:'Model',exact:true}).inputValue(),'E-II');
  assert.equal(await page.locator('.guitar-tuning-list>div').count(),4); await button('Cancel').click();
  await page.getByRole('button',{name:/^All songs/}).click();
  await button('Edit Repeat loop study details').click();
  await page.getByRole('checkbox',{name:'ESP test',exact:true}).check(); await button('Save changes').click();
  await button('Guitars').click(); await button('Open ESP test collection').click();
  await button('Open Drop B♭ collection').click(); assert.equal(await page.locator('.song-card').count(),1);
  await button('Edit guitar ESP test').click(); await page.getByRole('textbox',{name:'Guitar name',exact:true}).fill('ESP baritone'); await button('Save guitar').click();
  await page.getByRole('dialog').waitFor({state:'detached'});
  assert.deepEqual((await librarySong()).guitars,[], 'Tuning matches are derived; renaming must not create a permanent manual assignment');
  await button('Open Drop B♭ collection').click(); assert.equal(await page.locator('.song-card').count(),1);
  assert.deepEqual(errors, []);
  console.log('PASS: guitar details and multiple tuning folders persist across reloads.');
  console.log('PASS: individual note selection, fret edits, annotations, transposition, fingering preview/application, undo, retuning, edited GP export, persistence and narrow layout. No page errors.');
} catch (error) { await page.screenshot({ path: 'test-results/v5-failure.png' }); console.error('Page errors:', errors); console.error((await page.locator('body').innerText()).slice(-2500)); throw error; }
finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
