param([Parameter(Mandatory=$true)][string]$Script,[Parameter(Mandatory=$true)][string]$Plan)
$ErrorActionPreference='Stop'
# Shell-launch a hidden installer independently of Electron's child process job.
# Both arguments are paths generated by this app; quote them as literal arguments.
if ($Script.Contains('"') -or $Plan.Contains('"')) { throw 'Invalid installer path.' }
$powershell=Join-Path $env:SystemRoot 'System32/WindowsPowerShell/v1.0/powershell.exe'
$arguments='-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$Script+'" -Plan "'+$Plan+'"'
Start-Process -FilePath $powershell -ArgumentList $arguments -WorkingDirectory ([IO.Path]::GetDirectoryName($Plan)) -WindowStyle Hidden | Out-Null
