export function base64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
export function unbase64(value){if(typeof value!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(value))throw new Error('Invalid encrypted message.');return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}
export function newSecret(){return base64(crypto.getRandomValues(new Uint8Array(32)));}
async function key(secret){const bytes=unbase64(secret);if(bytes.length!==32)throw new Error('Invalid pairing key.');return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']);}
const aad=new TextEncoder().encode('Guitar.io LAN v1');
export async function seal(secret,value){const nonce=crypto.getRandomValues(new Uint8Array(12)),data=new TextEncoder().encode(JSON.stringify(value)),body=await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:aad},await key(secret),data);return {v:1,nonce:base64(nonce),body:base64(new Uint8Array(body))};}
export async function open(secret,envelope){if(envelope?.v!==1)throw new Error('Incompatible sync protocol.');const nonce=unbase64(envelope.nonce);if(nonce.length!==12)throw new Error('Invalid nonce.');const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:nonce,additionalData:aad},await key(secret),unbase64(envelope.body));return JSON.parse(new TextDecoder().decode(bytes));}
export function privateIPv4(host){if(typeof host!=='string')return false;const parts=host.replace(/^::ffff:/,'').split('.').map(Number);if(parts.length!==4||!parts.every(n=>Number.isInteger(n)&&n>=0&&n<=255))return false;const [a,b]=parts;return a===10||a===127||a===192&&b===168||a===172&&b>=16&&b<=31||a===169&&b===254;}
export function localEndpoint(value){const url=new URL(value);if(url.protocol!=='http:'||!privateIPv4(url.hostname)||url.username||url.password||url.pathname!=='/sync'||url.search||url.hash||!url.port)throw new Error('Use a private LAN IPv4 address and the Guitar.io sync port.');return url.href;}
export function pairingCode(value){return 'guitario1:'+base64(new TextEncoder().encode(JSON.stringify(value)));}
export function parsePairing(value){if(typeof value!=='string'||value.length>6000||!value.trim().startsWith('guitario1:'))throw new Error('Paste a Guitar.io pairing code.');const item=JSON.parse(new TextDecoder().decode(unbase64(value.trim().slice(10))));if(item.v!==1||typeof item.id!=='string'||item.id.length>200||typeof item.name!=='string'||item.name.length>100||unbase64(item.secret).length!==32||!Array.isArray(item.endpoints)||!item.endpoints.length||item.endpoints.length>20)throw new Error('Invalid pairing code.');item.endpoints=item.endpoints.map(localEndpoint);return item;}
