import { useEffect, useRef, useState } from 'react';
import { GripHorizontal, Highlighter, Trash2 } from 'lucide-react';
import type { AnnotationPosition } from './types';
export type VisibleAnnotation={id:string;text:string;color:string;anchor:AnnotationPosition;name:string};
export default function SheetAnnotation({item,position,onMove,onText,onColor}:{item:VisibleAnnotation;position?:AnnotationPosition;onMove:(p:AnnotationPosition)=>Promise<void>;onText:(text:string)=>Promise<void>;onColor:(color:string)=>Promise<void>}) {
  const [temporary,setTemporary]=useState<AnnotationPosition|null>(null),[text,setText]=useState(item.text),[colors,setColors]=useState(false);
  const input=useRef<HTMLTextAreaElement>(null),drag=useRef<{x:number;y:number;start:AnnotationPosition}|null>(null),saved=useRef(item.text);
  useEffect(()=>{saved.current=item.text;if(document.activeElement!==input.current)setText(item.text);},[item.text]);
  useEffect(()=>{if(!item.text)input.current?.focus();},[]);
  const offset=temporary || position || {x:0,y:0},offsetRef=useRef(offset),moveRevision=useRef(0);offsetRef.current=offset;
  function move(next:AnnotationPosition){const revision=++moveRevision.current;offsetRef.current=next;setTemporary(next);return onMove(next).finally(()=>{if(moveRevision.current===revision)setTemporary(null);});}
  function save(){if(text!==saved.current){saved.current=text;void onText(text);}}
  return <div className="sheet-annotation free-text-note" data-annotation-id={item.id} style={{left:Math.max(4,item.anchor.x+offset.x),top:Math.max(2,item.anchor.y+offset.y),'--annotation-color':item.color} as React.CSSProperties}>
    <div className="annotation-utilities"><button className="annotation-drag" aria-label="Move text note" title="Drag to move; arrow keys move 5 pixels" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();const step=e.shiftKey?20:5;void move({x:offsetRef.current.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),y:offsetRef.current.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)});}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();save();e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,start:offsetRef.current};}} onPointerMove={e=>{const d=drag.current;if(d)setTemporary({x:Math.max(-item.anchor.x+4,Math.min(10000,d.start.x+e.clientX-d.x)),y:Math.max(-item.anchor.y+2,Math.min(10000,d.start.y+e.clientY-d.y))});}} onPointerUp={e=>{const d=drag.current;if(!d)return;drag.current=null;const next={x:Math.max(-item.anchor.x+4,Math.min(10000,d.start.x+e.clientX-d.x)),y:Math.max(-item.anchor.y+2,Math.min(10000,d.start.y+e.clientY-d.y))};void move(next);}} onPointerCancel={()=>{drag.current=null;setTemporary(null);}}><GripHorizontal size={15}/></button><button aria-label="Highlight text note" onClick={()=>setColors(v=>!v)}><Highlighter size={14}/></button><button aria-label="Delete text note" onClick={()=>void onText('')}><Trash2 size={13}/></button></div>
    <textarea ref={input} aria-label="Text note" rows={Math.max(1,text.split('\n').length)} maxLength={4000} value={text} style={{width:`${Math.min(45,Math.max(12,...text.split('\n').map(line=>line.length)))}ch`}} onChange={e=>setText(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==='Enter' && !e.shiftKey){e.preventDefault();save();e.currentTarget.blur();}if(e.key==='Escape'){e.stopPropagation();setText(item.text);e.currentTarget.blur();}}}/>
    {colors && <div className="annotation-colors">{['#efc666','#9ed2b0','#94c4f2','#d4a3e8','#f0a5ba','#ffffff'].map(color=><button key={color} aria-label={`Highlight ${color}`} title={color} style={{background:color}} onClick={()=>{void onColor(color);setColors(false);}}/>)}</div>}
  </div>;
}
